"""
Introdução ao try/except
try > tentar executar
except > ocorreu um erro
"""

try:
    print('Teste')
except:
    print('ERRO print Teste')